# fly.toml app configuration file generated for aggregator-green-star-582 on 2024-10-30T22:46:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aggregator-green-star-582'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[redis]
  name = 'aggregator-green-star-582-redis'
  org = 'personal'
  region = 'otp'
  disable_eviction = true
  no_replicas = true
